### ISSUE TITLE
How to set default culture?

### ISSUE THREAD

**Issue by faresayyad** [LazZiya/XLocalizer#29]
Hello, 

I am wondering how can I set a default culture for all routes if culture value isn't provided in the URL!
As you can see here the Identity razor page is working well without explicitly specifying the culture value.
![image](https://user-images.githubusercontent.com/11721949/147708822-5a180737-dc7a-4766-a5c2-41128b010005.png)

Whereas in a view like this (controller - view) the page isn't working unless I explicitly provide a culture in the URL.
![image](https://user-images.githubusercontent.com/11721949/147708885-b0bf8ada-83a8-4985-b069-f707d7fb877e.png)

Thank you!!!

**Comment by LazZiya** [comment]
Hi @faresayyad ,

You need to setup multiple routes for the pages w/o culture parameter. e.g.:

````cs
[Route("")]
[Route("{culture}")]
[Route("{culture}/Home/Index")]
[Route("{culture}/Home/Index/{id?}")]
````

In order to avoid route conflicts, remove the code that automatically add culture param to all routes in startup:

````cs
services.AddRazorPages()
    // remove below line for razor pages setup
    // .AddRazorPagesOptions(ops => { ops.Conventions.Insert(0, new RouteTemplateModelConventionRazorPages()); });
    // or mvc setup
    // .AddMvcOptions(ops => { ops.Conventions.Insert(0, new RouteTemplateModelConventionMvc()); });
````

Last, I recommend to setup the culture cookie, so even if the route is not defined in the URL in this case `XLocalizer` will look for the route value in the cookie.
````cs
// Add required namespaces
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

/// <summary>
/// Set culture cookie value
/// </summary>
/// <param name="cltr">Culture name</param>
/// <param name="returnUrl">The url to return to after setting the cookie</param>
public IActionResult OnGetSetCultureCookie(string cltr, string returnUrl)
{
    Response.Cookies.Append(
        CookieRequestCultureProvider.DefaultCookieName,
        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cltr)),
        new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
    );

    return LocalRedirect(returnUrl);
}
````

For more details see:
- [LanguageNavTagHelper](https://docs.ziyad.info/en/LazZiya.TagHelpers/v6.0/LanguageNav-TagHelper-Setup.md#set-culture-cookie)
- [XLocalizer culture fallback behavior](https://docs.ziyad.info/en/XLocalizer/v1.0/culture-fallback-behavior.md)

**Comment by LazZiya** [comment]
I hope my answer has solvved your issue, 
feel free to reopen if needed.
