### ISSUE TITLE
FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by faresayyad** [LazZiya/XLocalizer#40]
Hello, 

**I have a decimal property in the model** 
![image](https://user-images.githubusercontent.com/11721949/211816219-5199e872-a646-4496-aeb5-cda0bbe9c559.png)

**When I switch to the Arabic language error is thrown like this:**
![image](https://user-images.githubusercontent.com/11721949/211815850-00a9da07-13c5-4e54-b68b-7c89670d7c6b.png)

----------------------------------------------------

![image](https://user-images.githubusercontent.com/11721949/211816348-6ad066d0-5bde-4ec6-ba0c-a36adab26845.png)

**Comment by LazZiya** [comment]
Can you check the Arabic translations in the resource file? There could be a conflict due to decimal number format (comma) `0,00` and (period) `0.00`.

Again you also need to take care of the input field numbering format and validation, because the Arabic culture will accept Arabic (previously known as Hindu) digits `٠١٢٣٤٥٦٧٨٩` but the default input is Latin (previously known as Arabic) digits `0123456789`, so you may want to amend the accepted input for Arabic culture to accept Latin digits.

read more here about number systems and how to setup client side validation:
- [Client side validation](https://ziyad.info/en/articles/19-Client_Side_Validation)
- [Multi cultural numbering systems](https://ziyad.info/en/articles/26-Multicultural_Numbering_Systems)
- [Live demo - form input in different numbering systems](https://demo.ziyad.info/en/NumberingSystems)

**Comment by faresayyad** [comment]
Thank you for your response.
Actually, I didn't insert any number in the field yet.
i changed the language from the drop down list 


![image](https://user-images.githubusercontent.com/11721949/212029261-9e22e653-84b2-46ab-a817-7285055764cc.png)


Then the exception thrown

**Comment by LazZiya** [comment]
Did you checked the resource file for the translated resource name? also check the translated model binding and data annotations messages.

**Comment by faresayyad** [comment]
I am using XML with MyMemmoryTranslate service:
The translation file:

![image](https://user-images.githubusercontent.com/11721949/212035058-cc596015-4b17-478f-9b40-1ba58898950a.png)

**Comment by LazZiya** [comment]
What about data annotations and model binding errors? do you have them translated?

**Comment by faresayyad** [comment]
What do you mean by data annotations translation and model binding  !?

**Comment by LazZiya** [comment]
See [Validation errors](https://docs.ziyad.info/en/XLocalizer/v1.0/localizing-validation-attributes-errors.md) and [Model binding errors](https://docs.ziyad.info/en/XLocalizer/v1.0/model-binding-errors.md).

Those error messages could have some invalid translation causing comma and period conflict in different cultures. Search the XML file for any relevant one.

**Comment by faresayyad** [comment]
The XML File don't have any ModelBinding translation !

**Comment by faresayyad** [comment]
I mean the XML file contains only one translation regarding the two fields 

![image](https://user-images.githubusercontent.com/11721949/212051808-d0b50ff3-bce3-440f-a68f-f146f39d64a8.png)


![image](https://user-images.githubusercontent.com/11721949/212051952-9e42d44e-1da7-4691-bfe3-9d05bafbe23b.png)
